spring:
  application:
    name: PruebaTecnica
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:prueba
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mvc:
    favicon:
      enabled: false
